name: "Build & Release"
on:
  release:
    types: [ created ]

jobs:
  sign:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@a28b4ba2f491cc36c67a714a716ca54218440056
        with:
          cmd: build
          source: src

      - name: "Sync time"
        run: |
          timedatectl;
          date;
          sudo timedatectl set-ntp off
          sudo timedatectl set-ntp on
          timedatectl;
          date;

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@a28b4ba2f491cc36c67a714a716ca54218440056
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: "Rename binary"
        run: |
          mv web-ext-artifacts/*.xpi Extension-Build.xpi
          ls

      - name: "Upload binaries to release"
        uses: svenstaro/upload-release-action@133984371c30d34e38222a64855679a414cb7575
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Extension-Build.xpi
          tag: ${{ github.ref }}
          overwrite: true

      - name: "Remove the pre-release tag"
        uses: tubone24/update_release@6b5e0283cae1ce14b411f0f027c24d24d90c1477
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          prerelease: false
