name: "Build & Release"
on:
  release:
    types: [ created ]

jobs:
  sign:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src

      - name: "Sync time"
        run:
          timedatectl;
          date;
          sudo timedatectl set-ntp off
          sudo timedatectl set-ntp on
          timedatectl;
          date;

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: "Rename binary"
        run:
          mv *.xpi Extension-Build.xpi
          ls

      - name: "Add binaries to the release"
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'Extension-Build.xpi'
